cluster_feedback:
  ros__parameters:
    robot_id_list: ["p2", "p3", "p4"]
    cluster_size: 3
    cluster_params: [8.0, 8.0, 1.047]
    adaptive_navigation: True
    cluster_type: "TriangleatCentroid"