cluster_feedback:
  ros__parameters:
    robot_id_list: ["p1", "p2", "p3", "p4", "p5"]
    cluster_size: 5 #number of robots to use
    cluster_type: "PentagonatLeader"
    cluster_params: [3.0,3.0,3.0,3.0,0.0,0.0,0.0]
    control_mode: "VEL"  